### ISSUE TITLE
v4.9.{62…64}-unofficial_grsec fail with gcc version 6.4.0

### ISSUE THREAD

**Issue by powerman** [minipli/linux-unofficial_grsec#15]
```
# make
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  DESCEND  objtool
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
make[1]: [grsecurity/Makefile:50: grsecurity/grsec_hidesym.o] Error 1 (ignored)
  grsec: protected kernel image paths
  CC      sound/core/seq/oss/seq_oss_readq.o
sound/core/seq/oss/seq_oss_readq.c: In function 'snd_seq_oss_readq_sysex':
sound/core/seq/oss/seq_oss_readq.c:146:36: error: passing argument 2 of 'snd_seq_dump_var_event' from incompatible pointer type [-Werror=incompatible-pointer-types]
  return snd_seq_dump_var_event(ev, readq_dump_sysex, &ctx);
                                    ^~~~~~~~~~~~~~~~
In file included from ./include/sound/seq_oss.h:25:0,
                 from sound/core/seq/oss/seq_oss_device.h:29,
                 from sound/core/seq/oss/seq_oss_readq.h:25,
                 from sound/core/seq/oss/seq_oss_readq.c:23:
./include/sound/seq_kernel.h:87:5: note: expected 'snd_seq_dump_func_t {aka int (*)(void *, const void *, int)}' but argument is of type 'int (*)(void *, void *, int)'
 int snd_seq_dump_var_event(const struct snd_seq_event *event,
     ^~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:294: sound/core/seq/oss/seq_oss_readq.o] Error 1
make[3]: *** [scripts/Makefile.build:544: sound/core/seq/oss] Error 2
make[2]: *** [scripts/Makefile.build:544: sound/core/seq] Error 2
make[1]: *** [scripts/Makefile.build:544: sound/core] Error 2
make: *** [Makefile:993: sound] Error 2
```

Thanks for maintaining grsec for 4.9!

**Comment by powerman** [comment]
4.9.59 and 4.9.61 works ok with gcc-6.4.0.

**Comment by minipli** [comment]
Thanks for the report! I had `CONFIG_SND_SEQUENCER_OSS` disabled in my build so didn't noticed that one.

It's fixed with commit `963c044d9f16 ("[pax] ALSA: seq_oss: fix prototype of readq_dump_sysex()")` -- not tagged yet, though. But you can just build the HEAD of the `linux-4.9.x-unofficial_grsec` branch.
